name = "UlamMethod"
uuid = "4cc20838-1966-48f0-823a-5def0ad5c24d"
authors = ["Gage Bonner"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
